modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="true_end"
version="${modVersion}"
displayName="True End"
displayURL="""

https://modrinth.com/mod/true_end
https://www.curseforge.com/minecraft/mc-mods/true-end-cf
"""
logoFile="icon.png"
authors="Mystic Creations Team"
description="But it was all a dream"

[[mixin]]
mixinClasses = ["net.mysticcreations.true_end.mixin.Mixins"]

[[dependencies.true_end]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraftVersion}]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.true_end]]
    modId="terrablender"
    mandatory=true
    versionRange="[${terrablenderVersion},)"
    ordering="NONE"
    side="BOTH"
[[dependencies.true_end]]
    modId="curios"
    mandatory=false
    versionRange="*"
    ordering="NONE"
    side="BOTH"
[[dependencies.true_end]]
    modId="nostalgic_tweaks"
    mandatory=false
    versionRange="*"
    ordering="NONE"
    side="BOTH"
